Add example of authenticating a GitHub app
XAMPPRocky/octocrab pull request #111
Opened 2021-09-10 01:00 UTC by chinedufn

This commit adds an example of authenticating a GitHub app.

It also adds a new method `create_authenticate_as_app_jwt` to the public
API.

2021-09-10 01:00 UTC, chinedufn commented
Related: https://github.com/XAMPPRocky/octocrab/issues/1#issuecomment-916383237

2021-09-10 01:03 UTC, chinedufn commented on examples/github_app_authentication.rs
> +        .create_comment(0, "Created programmatically!")
Won't actually do anything since there is no issue 0

2021-09-10 23:42 UTC, chinedufn commented on examples/github_app_authentication.rs
> +    let access: InstallationToken = octocrab
This fails to deserialize. Looks like the returned Permissions struct is missing the `admin` field.

Can I add `#[serde(default)]` to the admin field in the `Permissions` struct?

2021-09-11 00:55 UTC, chinedufn commented on examples/github_app_authentication.rs
> +    let access: InstallationToken = octocrab
Done

2021-09-13 15:32 UTC, XAMPPRocky requested changes
Thank you for your PR! The code is mostly there, it just needs to cleaned up to be aligned with the rest of the codebase. Feel to ask if you have any questions.

2021-09-13 15:32 UTC, XAMPPRocky commented on examples/github_app_authentication.rs
> +        .unwrap();
Can we use something related to apps or installations instead and be read-only if possible?

2021-09-13 15:32 UTC, XAMPPRocky commented on examples/github_app_authentication.rs
> +    dbg!(comment);
```suggestion
```

2021-09-13 15:32 UTC, XAMPPRocky commented on src/auth/apps.rs
> +use jsonwebtoken::{encode, Algorithm, EncodingKey, Header};
Can we move this into `src/auth.rs` directly instead?
```suggestion
use jsonwebtoken::{Algorithm, EncodingKey, Header};
```

2021-09-13 15:32 UTC, XAMPPRocky commented on src/auth/apps.rs
> +    let key = EncodingKey::from_rsa_pem(private_key.as_bytes())?;
This shouldn't be stringly typed. `app_id` is a number, and `private_key` is a bag of bytes. Using `A: AsRef<[u8]>` allows us to accept any type which can be referenced as a bag of bytes.

```suggestion
pub fn create_jwt<A: AsRef<[u8]>>(
    github_app_id: AppId,
    private_key: A,
) -> Result<String, jsonwebtoken::errors::Error> {
    let key = EncodingKey::from_rsa_pem(private_key.as_ref())?;
```

2021-09-13 15:32 UTC, XAMPPRocky commented on src/auth/apps.rs
> +    encode(&header, &claims, &key)
Personal preference, I don't like calling imported functions like this, I always like to have them prefixed. The first thing I think when I see this is code is "Who's encode is this?".

```suggestion
    jsonwebtoken::encode(&header, &claims, &key)
```

2021-09-13 23:25 UTC, chinedufn commented
Thanks for the feedback!

All feedback addressed.

When everything checks out I can rebase.

2021-09-17 08:19 UTC, XAMPPRocky approved these changes
LGTM! Just have one last small change around the importing `create_jwt`

2021-09-17 08:19 UTC, XAMPPRocky commented on examples/github_app_authentication.rs
> +    let token = create_jwt(app_id.parse::<u64>().unwrap().into(), app_private_key).unwrap();
```suggestion
use octocrab::Octocrab;

#[tokio::main]
async fn main() -> octocrab::Result<()> {
    let app_id = read_env_var("GITHUB_APP_ID");
    let app_private_key = read_env_var("GITHUB_APP_PRIVATE_KEY");

    let token = octocrab::auth::create_jwt(app_id.parse::<u64>().unwrap().into(), app_private_key).unwrap();
```

2021-09-17 08:19 UTC, XAMPPRocky commented on src/lib.rs
> +    auth::create_jwt,
```suggestion
```

2021-09-17 08:22 UTC, XAMPPRocky commented
Just going to apply the suggestions now, and get this merged so I can make a new release.

2021-09-17 22:58 UTC, merged

2021-09-17 22:58 UTC, XAMPPRocky commented
Thank you for your PR!