Box webhook event payload variants
XAMPPRocky/octocrab pull request #114
Opened 2021-09-12 06:50 UTC by chinedufn

Closes https://github.com/XAMPPRocky/octocrab/issues/113

2021-09-12 08:01 UTC, XAMPPRocky requested changes
Looks good to me, I have two minor comments that I'd like to address and then we can merge this.

2021-09-12 08:01 UTC, XAMPPRocky commented on src/models/events.rs
>          _ => EventPayload::UnknownEvent(data),
```suggestion
        _ => EventPayload::UnknownEvent(Box::new(data)),
```

2021-09-12 16:09 UTC, chinedufn commented
All feedback addressed and rebased!

2021-09-13 14:22 UTC, XAMPPRocky commented
Thank you for your PR, and congrats on your first contribution! 🎉

2021-09-13 14:22 UTC, merged